from .softonic.Softonic import Softonic
from .appsapk.Appsapk import AppsApk
from .gofood.Gofood import Gofood
from .uptodown.Uptodown import Uptodown
from .misterAladin.MisterAladin import MisterAladin
from .indeed.Indeed import Indeed
from .fourShared.FourShared import FourShared
from .download.Download import Download
from .jihadimalmo.Jihadimalmo import Jihadimalmo
from .theReligionOfPeace.TheReligionOfPeace import TheReligionOfPeace
from .archive.Archive import Archive
from .bri.Bri import Bri
from .bankmandiri.Bankmandiri import Bankmandiri
from .btn.Btn import Btn